import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '@/trpc/react';

import type { Metadata } from 'next';

import '@/styles/globals.css';

export const metadata: Metadata = {
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
  title: 'Create T3 App',
};

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      className={`
        ${geist.variable}
      `}
      lang="zh-Hant"
    >
      <body>
        <TRPCReactProvider>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
